apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-k-datadog
  namespace: map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-service-k-datadog
  template:
    metadata:
      labels:
        app: py-service-k-datadog
    spec:
      containers:
      - name: service-k
        image: 104013952213.dkr.ecr.eu-north-1.amazonaws.com/aharon-flask-app:map-service-datadog-k-v6
        ports:
        - containerPort: 5000
        env:
        - name: DD_AGENT_HOST
          value: "datadog-agent.dd.svc.cluster.local"
        - name: DD_TRACE_AGENT_URL
          value: "http://datadog-agent.dd.svc.cluster.local:8126"
        - name: SERVICE_B_URL
          value: "http://service-b-datadog:5001"
        - name: SERVICE_PORT
          value: "5000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-k-datadog
  namespace: map
spec:
  selector:
    app: py-service-k-datadog
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP