apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-j
  namespace: map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-service-j
  template:
    metadata:
      labels:
        app: py-service-j
      # annotations:
        # instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: service-j
        image: 104013952213.dkr.ecr.eu-north-1.amazonaws.com/aharon-flask-app:map-service-j-v1
        ports:
        - containerPort: 5002
        env:
        - name: SERVICE_B_URL
          value: "http://service-b:5001"
        - name: SERVICE_PORT
          value: "5002"
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(OTEL_IP):4318"
        - name: OTEL_SERVICE_NAME
          value: "py-service-j"
        # Auto-injection environment variables
        - name: OTEL_PYTHON_LOG_CORRELATION
          value: "true"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-j
  namespace: map
spec:
  selector:
    app: py-service-j
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP