apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-t
  namespace: map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-service-t
  template:
    metadata:
      labels:
        app: py-service-t
      # annotations:
        # instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: service-t
        image: 104013952213.dkr.ecr.eu-north-1.amazonaws.com/aharon-flask-app:map-service-t-v1
        ports:
        - containerPort: 5004
        env:
        - name: SERVICE_PORT
          value: "5004"
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(OTEL_IP):4318"
        - name: OTEL_SERVICE_NAME
          value: "py-service-t"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-t
  namespace: map
spec:
  selector:
    app: py-service-t
  ports:
  - port: 5004
    targetPort: 5004
  type: ClusterIP